### PR TITLE
Update lodash due to possible security issue

### PR DESCRIPTION
**Pull request by manuelbieh**
Source: https://www.npmjs.com/advisories/577

Lodash versions prior to 4.17.5 are affected so I updated it to 4.17.10. Tests are all still passing so I think this could be safely merged.

### CODE REVIEW

**Comment by pascalstr** [comment]
@danethurber could you have a look at this PR please?

**Comment by pmcalmeida** [comment]
Is anyone maintaining this repo?!

**Comment by aliankarali** [comment]
@danethurber, are you still with us mate?

**Comment by danethurber** [comment]
👍

**Comment by manuelbieh** [comment]
Awesome, thanks!

**Pull request merged**
